### ISSUE TITLE
ftdetect fails to override on Debian 7 Wheezy

### ISSUE THREAD

**Issue by cengizIO** [wting/rust.vim#10]
Hi there,

I'm using Vundle on Debian 7.5 Wheezy with the following configuration

    VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Feb 10 2013 02:28:47)
    Included patches: 1-547
    Modified by pkg-vim-maintainers@lists.alioth.debian.org
    Compiled by jamessan@debian.org
    Huge version without GUI.  Features included (+) or not (-):
    +arabic +autocmd -balloon_eval -browse ++builtin_terms +byte_offset +cindent 
    -clientserver -clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments 
    +conceal +cryptv +cscope +cursorbind +cursorshape +dialog_con +diff +digraphs 
    -dnd -ebcdic +emacs_tags +eval +ex_extra +extra_search +farsi +file_in_path 
    +find_in_path +float +folding -footer +fork() +gettext -hangul_input +iconv 
    +insert_expand +jumplist +keymap +langmap +libcall +linebreak +lispindent 
    +listcmds +localmap +lua +menu +mksession +modify_fname +mouse -mouseshape 
    +mouse_dec +mouse_gpm -mouse_jsbterm +mouse_netterm -mouse_sysmouse 
    +mouse_xterm +mouse_urxvt +multi_byte +multi_lang -mzscheme +netbeans_intg 
    +path_extra +perl +persistent_undo +postscript +printer +profile +python 
    -python3 +quickfix +reltime +rightleft +ruby +scrollbind +signs +smartindent 
    -sniff +startuptime +statusline -sun_workshop +syntax +tag_binary 
    +tag_old_static -tag_any_white +tcl +terminfo +termresponse +textobjects +title
     -toolbar +user_commands +vertsplit +virtualedit +visual +visualextra +viminfo 
    +vreplace +wildignore +wildmenu +windows +writebackup -X11 -xfontset -xim -xsmp
     -xterm_clipboard -xterm_save 
       system vimrc file: "$VIM/vimrc"
         user vimrc file: "$HOME/.vimrc"
          user exrc file: "$HOME/.exrc"
      fall-back for $VIM: "/usr/share/vim"
    Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1     -I/usr/include/tcl8.5  -D_REENTRANT=1  -D_THREAD_SAFE=1  -D_LARGEFILE64_SOURCE=1  
    Linking: gcc   -L. -Wl,-z,relro -rdynamic -Wl,-export-dynamic  -Wl,-E  -Wl,-z,relro -Wl,--as-needed -o vim       -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm  -L/usr/lib -llua5.1  -Wl,-E  -fstack-protector -L/usr/local/lib  -L/usr/lib/perl/5.14/CORE -lperl -ldl -lm -lpthread -lcrypt -L/usr/lib/python2.7/config -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions  -L/usr/lib -ltcl8.5 -ldl -lpthread -lieee -lm -lruby-1.9.1 -lpthread -lrt -ldl -lcrypt -lm  -L/usr/lib   

I'm using HEAD version of all plugins and here's my .vimrc

    set nocompatible
    filetype off
    
    set rtp+=~/.vim/bundle/Vundle.vim
    call vundle#begin()
    
    "Plugin 'tpope/vim-fugitive'
    Plugin 'gmarik/Vundle.vim'
    Plugin 'flazz/vim-colorschemes'
    Plugin 'Syntastic'
    Plugin 'tpope/vim-sensible'
    Plugin 'bling/vim-airline'
    Plugin 'surround.vim'
    Plugin 'mileszs/ack.vim'
    Plugin 'ervandew/supertab'
    Plugin 'Lokaltog/vim-easymotion'
    Plugin 'kien/ctrlp.vim'
    Plugin 'jceb/vim-orgmode'
    Plugin 'speeddating.vim'
    Plugin 'wting/rust.vim'
    
    call vundle#end()
    filetype plugin indent on
    
    "Syntastic
    let g:syntastic_enable_perl_checker = 1
    let g:syntastic_check_on_open=1
    let g:syntastic_enable_balloons=1
    "let g:syntastic_always_populate_loc_list=1
    "let g:syntastic_echo_current_error=1
    let g:syntastic_enable_highlighting=1
    "let g:syntastic_auto_jump=1
    "let g:syntastic_auto_loc_list=1
    "let g:syntastic_loc_list_height=5
    "let g:syntastic_aggregate_errors=1
    "let g:syntastic_id_checkers=1

    highlight SyntasticErrorLine guibg=#6D6968 
    highlight SyntasticWarningLine guibg=#6D6968 
    let g:syntastic_enable_signs=1
    let g:syntastic_error_symbol="E>"
    let g:syntastic_warning_symbol="W>"
    
    let g:airline_left_sep = ''
    let g:airline_left_alt_sep = ''
    let g:airline_right_sep = ''
    let g:airline_right_alt_sep = ''
    let g:airline_powerline_fonts = 1
    let g:airline_theme = 'wombat'
    
    syntax on
    autocmd BufWrite * mkview
    autocmd BufRead * silent loadview
    set backup
    set backupdir=~/.vim/tmp
    set dir=~/.vim/tmp
    set tabstop=4 shiftwidth=4 expandtab
    set laststatus=2
    set hlsearch
    set ic
    set noshowmode
    set timeoutlen=50
    colorscheme blackdust-vivify
    
    " -----------------------------------------------------------------
    " This is my workaround, which irritates me so much
    " -----------------------------------------------------------------
    au BufRead,BufNewFile *.rs set filetype=rust

Unless I include that last line (which already exists in your **ftdetect/rust.vim**) `*.rs` files are detected as `hercules` files.

I've found a filetype definition on `*.rs` in `/usr/share/vim/vim73/filetype.vim` however deleting that did not solve my problem.

Any suggestions?

**Comment by wting** [comment]
Closing all issues because there now exists an official [rust.vim](https://github.com/rust-lang/rust.vim).
