### ISSUE TITLE
Syntastic file checker reporting few errors

### ISSUE THREAD

**Issue by oblitum** [wting/rust.vim#21]
Hi, I've gone through all the discussion that happened some months back about the move that happened to the syntastic checker. The thing is, I just pulled rust alpha and updated everything. The buffer's filetype is `rust`, `g:syntastic_extra_filetypes` contains rust, `g:loaded_syntastic_rust_rustc_checker` is `1`. Despite this, I don't get any checking when I `:w` a file.

I'm on OS X, Vim 7.4.383.

Is there any more setup I should do for it to work?

cc @BurntSushi

**Comment by BurntSushi** [comment]
I don't use OS X, but I'm using this package and It Just Works: https://aur.archlinux.org/packages/vim-rust-git/ (It looks like it pulls from this repo)

**Comment by oblitum** [comment]
I'm getting diagnostics after making my `.vimrc` empty, I'll bisect the offending configuration. If it has anything to do to fix here I'll reopen, thanks.

**Comment by oblitum** [comment]
My bad, when I thought syntastic was reporting diagnostics correctly after empting my `.vimrc` and editing some rust file, the error reported by syntastic was unrelated to being generated by `rustc`. It seems syntastic warns about non-matching parentheses by itself, and so I thought it was working with `rustc` when I saw the error report, but it wasn't. Trying it again by using a non-declared variable in the rust file instead of deleting a brace with an "empty" `.vimrc` just with the following does not report any error:

```vim
" VIM-PLUG Setup {{{

call plug#begin('~/.vim/plugged')

" Plugins {{{
Plug 'scrooloose/syntastic'
Plug 'tpope/vim-sensible'
Plug 'wting/rust.vim'
" }}}

call plug#end()

" Plugin Preloading {{{
runtime! plugin/sensible.vim
" }}}

" }}}
```

**Comment by oblitum** [comment]
Ah, in truth, after deleting `Plug 'wting/rust.vim'`, syntastic _does not_ warn about any error related to unmatched parentheses in rust files... So, the error about unmatched parentheses should be coming from `rustc` indeed. Now I dunno why I don't get any other kind of error reported.

**Comment by oblitum** [comment]
Isn't because of this `abort` behavior? is it new?:

```
❯❯❯ vim sample.rs                                                                                                  
❯❯❯ rustc sample.rs
sample.rs:1:12: 1:13 error: incorrect close delimiter: `)`
sample.rs:1 pub fn main) {
                       ^
❯❯❯ vim sample.rs                         
❯❯❯ rustc sample.rs                       
sample.rs:2:5: 2:12 error: unresolved name `dasdada`
sample.rs:2     dasdada
                ^~~~~~~
error: aborting due to previous error
```

**Comment by oblitum** [comment]
Was able to produce another error that was captured by Syntastic:

```
sample.rs:1:9: 1:10 error: unexpected token: `,`
sample.rs:1 fn main(,) {
```

It seems the errors that leads to an abort don't get reports.

**Comment by oblitum** [comment]
My best bet is that that output is not matching `errorformat` in `SyntaxCheckers_rust_rustc_GetLocList`.

**Comment by corymickelson** [comment]
I have noticed this as well. Now maybe my assumptions are off. I Frequently switch between emacs and vim, and was alarmed when none of the errors picked up by emacs flycheck where shown in vim. I don't know if vim is less capable than emacs on this, or if there is something else going on. When I check SyntasticInfo It shows that the current file type is rust and that it will be checked automatically with rustc, but as stated earlier... there are a lot of errors getting through.

**Comment by wting** [comment]
Closing all issues because there now exists an official [rust.vim](https://github.com/rust-lang/rust.vim).
