### ISSUE TITLE
(Request) Feature Documentation

### ISSUE THREAD

**Issue by belph** [wting/rust.vim#22]
I understand that a true Vim pro would go through the codebase themselves and figure out all of the things this plugin does, but I nevertheless think that many could benefit from some amount of documentation of what this plugin provides. Even a simple list would be nice.

Thanks for the plugin, though. :smile:

**Comment by tafia** [comment]
:+1: 
I too think it would be very interesting to know exactly what this plugin does. I thought at the beginning it was just about syntax colorization. Then I discover there are some cargo stuff etc ...

**Comment by wting** [comment]
Closing all issues because there now exists an official [rust.vim](https://github.com/rust-lang/rust.vim).
