### ISSUE TITLE
filetype not detected?

### ISSUE THREAD

**Issue by mlooney** [wting/rust.vim#23]
rust.vim plugin loaded via pathogen, no other plugins installed (except syntastic). filetype is correctly set as "rust", but makeprg & efm is still the default "make". 

Calling "compiler cargo" or "compiler rustc" seems to set things up as expected though.  

Experimentally symlinking compiler/rustc.vim to compiler/rust.vim had no effect on the behavior.

**Comment by rdvdijk** [comment]
I also had this after installing the plugin via Vundle.

I fixed it by adding this to my `.vimrc`:

```
au BufRead *.rs try | execute "compiler rustc"
```

**Comment by wting** [comment]
Closing all issues because there now exists an official [rust.vim](https://github.com/rust-lang/rust.vim).
