### ISSUE TITLE
Repository is obsoleted by rust-lang/rust.vim

### ISSUE THREAD

**Issue by chris-morgan** [wting/rust.vim#25]
The decision has been made to split editor configurations out into their own repositories, so `src/etc/vim` on https://github.com/rust-lang/rust is now the repository https://github.com/rust-lang/rust.vim. This renders this repository obsolete.

**Comment by steveklabnik** [comment]
I would also like to say thank you, @wting , for keeping this mirror going. It'd be nice to contribute the README, maybe.

**Comment by wting** [comment]
Super busy these days with limited internet access, I'll update the README and shutdown the repository when I can.

Thanks @chris-morgan and @steveklabnik for your contributions as well!

**Comment by steveklabnik** [comment]
@wting thanks again for having made this repo in the first place, I know it helped a lot of people.
